# Generated by Django 5.0.6 on 2025-04-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pubDate', models.DateTimeField()),
                ('guid', models.URLField(unique=True)),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
